version: '3.3'

services:
  app:
    image: demo_app:latest
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=batchdb
      - MAIL_SERVER_HOST=smtp.gmail.com
      - MAIL_SERVER_PORT=587
      - MAIL_ACCOUNT=batchappdemo555@gmail.com
      - MAIL_PASSWORD=obtp phtd dyse egat
      - TARGET_MAIL=
      - DATA_PATH=/app/data/data.csv
      - SCHEMA_PATH=/app/basic_schema.json
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /home/a446123/devOps/demo_data:/app/data

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=batchdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
